### ISSUE TITLE
Request for Open Source Code Availability

### ISSUE THREAD

**Issue by lliai** [aaronserianni/training-free-nas#1]
Hello,

'm interested in contributing to its development. However, I noticed that the code is not currently available as open source.

I kindly request that you make the code available as soon as possible. As an open source advocate, I believe that making the code available to the public will benefit the software's development and promote transparency and collaboration within the community.

Please let me know if there are any plans to make the code available in the near future, and if there's anything I can do to help.

Thank you for your consideration.

Best regards,
Lujun

**Comment by aaronserianni** [comment]
Hello,

I just published the code used for our paper. Please let me know of any questions you may have.

**Comment by lliai** [comment]
Dear Aaronserianni,

I wanted to take a moment to express my gratitude for your prompt and thoughtful response. Your insights and suggestions were incredibly valuable and have helped me to move forward with greater clarity and confidence.

I truly appreciate your time and effort to provide me with such a detailed and insightful response. It means a lot to me that you were willing to share your expertise and experience, and I feel fortunate to have you as a resource.

Once again, thank you so much for your help and guidance. I look forward to staying in touch and continuing to learn from you in the future.

Best regards,
Lujun Li
